import { AbilityBuilder } from "@casl/ability";
import { createPrismaAbility } from "@casl/prisma";
import adminAbility from "./adminAbility";
import coordinatorAbility from "./coordinatorAbility";
import activeFacultyAbility from "./activeFacultyAbility";
import departmentAbility from "./departmentAbility";
import chairpersonReviewAbility from "./chairpersonReviewAbility";
import chairpersonReviewItemAbility from "./chairpersonReviewItemAbility";
import submittedChairpersonReviewAbility from "./submittedChairpersonReviewAbility";
import chairpersonSuggestionAbility from "./chairpersonSuggestionAbility";
import chairpersonSuggestionItemAbility from "./chairpersonSuggestionItemAbility";
import submittedChairpersonSuggestionAbility from "./submittedChairpersonSuggestionAbility";
import coordinatorReviewAbility from "./coordinatorReviewAbility";
import coordinatorReviewItemAbility from "./coordinatorReviewItemAbility";
import submittedCoordinatorReviewAbility from "./submittedCoordinatorReviewAbility";
import coordinatorSuggestionAbility from "./coordinatorSuggestionAbility";
import coordinatorSuggestionItemAbility from "./coordinatorSuggestionItemAbility";
import submittedCoordinatorSuggestionAbility from "./submittedCoordinatorSuggestionAbility";
import peerReviewAbility from "./peerReviewAbility";
import peerReviewItemAbility from "./peerReviewItemAbility";
import submittedPeerReviewAbility from "./submittedPeerReviewAbility";
import peerSuggestionAbility from "./peerSuggestionAbility";
import peerSuggestionItemAbility from "./peerSuggestionItemAbility";
import submittedPeerSuggestionAbility from "./submittedPeerSuggestionAbility";
import coordinatorEndorsementAbility from "./coordinatorEndorsementAbility";
import deanAbility from "./deanAbility";
import deanEndorsementAbility from "./deanEndorsementAbility";
import iMDCoordinatorSuggestionAbility from "./iMDCoordinatorSuggestionAbility";
import iMDCoordinatorSuggestionItemAbility from "./iMDCoordinatorSuggestionItemAbility";
import submittedIMDCoordinatorSuggestionAbility from "./submittedIMDCoordinatorSuggestionAbility";
import iMDCoordinatorEndorsementAbility from "./iMDCoordinatorEndorsementAbility";
import usersAbility from "./usersAbility";
import fileAbility from "./fileAbility";
import notificationAbility from "./notificationAbility";
import iMEventAbility from "./iMEventAbility";
import readNotificationAbility from "./readNotificationAbility";
import loginRoleAbility from "./loginRoleAbility";
import iMAbility from "./iMAbility";
import activeFileAbility from "./activeFileAbility";
import collegeAbility from "./collegeAbility";
import announcementAbility from "./announcementAbility";

export default async function userAbility(user) {
  const { can, cannot, build } = new AbilityBuilder(createPrismaAbility);

  adminAbility({ can, cannot, user });
  coordinatorAbility({ can, cannot, user });
  activeFacultyAbility({ can, cannot, user });
  activeFileAbility({ can, cannot, user });
  collegeAbility({ can, cannot, user });
  departmentAbility({ can, cannot, user });
  chairpersonReviewAbility({ can, cannot, user });
  chairpersonReviewItemAbility({ can, cannot, user });
  submittedChairpersonReviewAbility({ can, cannot, user });
  chairpersonSuggestionAbility({ can, cannot, user });
  chairpersonSuggestionItemAbility({ can, cannot, user });
  submittedChairpersonSuggestionAbility({ can, cannot, user });
  coordinatorReviewAbility({ can, cannot, user });
  coordinatorReviewItemAbility({ can, cannot, user });
  submittedCoordinatorReviewAbility({ can, cannot, user });
  coordinatorSuggestionAbility({ can, cannot, user });
  coordinatorSuggestionItemAbility({ can, cannot, user });
  submittedCoordinatorSuggestionAbility({ can, cannot, user });
  peerReviewAbility({ can, cannot, user });
  peerReviewItemAbility({ can, cannot, user });
  submittedPeerReviewAbility({ can, cannot, user });
  peerSuggestionAbility({ can, cannot, user });
  peerSuggestionItemAbility({ can, cannot, user });
  submittedPeerSuggestionAbility({ can, cannot, user });
  coordinatorEndorsementAbility({ can, cannot, user });
  deanAbility({ can, cannot, user });
  deanEndorsementAbility({ can, cannot, user });
  iMDCoordinatorSuggestionAbility({ can, cannot, user });
  iMDCoordinatorSuggestionItemAbility({ can, cannot, user });
  submittedIMDCoordinatorSuggestionAbility({ can, cannot, user });
  iMDCoordinatorEndorsementAbility({ can, cannot, user });
  usersAbility({ can, cannot, user });
  fileAbility({ can, cannot, user });
  notificationAbility({ can, cannot, user });
  iMEventAbility({ can, cannot, user });
  readNotificationAbility({ can, cannot, user });
  loginRoleAbility({ can, cannot, user });
  iMAbility({ can, cannot, user });
  announcementAbility({ can, cannot, user });

  // TODO ensure that peer, chairperson, dean, imd coordinator,
  // and citl director can still read suggestions, do the same on other resources
  return build();
}
