/*
  Warnings:

  - The values [IM_UPDATED] on the enum `IMEvent_IMEventType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterTable
ALTER TABLE `imevent` MODIFY `IMEventType` ENUM('IM_CREATED', 'NEW_VERSION', 'SUBMITTED_PEER_REVIEW', 'SUBMITTED_PEER_SUGGESTION', 'SUBMITTED_COORDINATOR_REVIEW', 'SUBMITTED_COORDINATOR_SUGGESTION', 'SUBMITTED_CHAIRPERSON_REVIEW', 'SUBMITTED_CHAIRPERSON_SUGGESTION', 'SUBMITTED_COORDINATOR_ENDORSEMENT', 'DEAN_ENDORSEMENT', 'SUBMITTED_IMD_COORDINATOR_SUGGESTION', 'IMD_COORDINATOR_ENDORSEMENT', 'CITL_DIRECTOR_ENDORSEMENT') NOT NULL;
