-- AlterTable
ALTER TABLE `im` MODIFY `status` ENUM('DRAFT', 'SUBMITTED', 'DEPARTMENT_REVIEWED', 'DEPARTMENT_REVISED', 'DEPARTMENT_ENDORSED', 'CITL_REVIEWED', 'CITL_REVISED', 'CITL_ENDORSED') NOT NULL DEFAULT 'DRAFT';
