-- AlterTable
ALTER TABLE `notification` ADD COLUMN `iMId` VARCHAR(191) NULL,
    MODIFY `Type` ENUM('SUBMITTED', 'SUBMITTED_PEER_REVIEW', 'SUBMITTED_CHAIRPERSON_REVIEW', 'SUBMITTED_COORDINATOR_REVIEW', 'SUBMITTED_PEER_SUGGESTION', 'SUBMITTED_CHAIRPERSON_SUGGESTION', 'SUBMITTED_COORDINATOR_SUGGESTION', 'DEPARTMENT_REVISED', 'COORDINATOR_ENDORSEMENT', 'DEAN_ENDORSEMENT', 'SUBMITTED_IMD_COORDINATOR_SUGGESTION', 'CITL_REVISED', 'IMD_COORDINATOR_ENDORSEMENT', 'CITL_DIRECTOR_ENDORSEMENT') NOT NULL;

-- CreateIndex
CREATE INDEX `Notification_iMId_idx` ON `Notification`(`iMId`);
